# Generated by Django 4.1.2 on 2023-03-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BizCont",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name1", models.CharField(max_length=200)),
                ("email1", models.EmailField(max_length=254)),
                ("phone1", models.CharField(max_length=200)),
            ],
        ),
    ]
