# Generated by Django 4.1.2 on 2023-03-10 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bizcontact", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bizcontact", old_name="email", new_name="bizemail",
        ),
        migrations.RenameField(
            model_name="bizcontact", old_name="name", new_name="bizname",
        ),
        migrations.RenameField(
            model_name="bizcontact", old_name="phone", new_name="bizphone",
        ),
    ]
